/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb786",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-container": "#b75b00",
        "on-secondary-fixed": "#171c1f",
        "on-primary-container": "#fefcff",
        "inverse-primary": "#adc6ff",
        "on-background": "#191c1e",
        error: "#ba1a1a",
        "on-secondary-container": "#5e6367",
        secondary: "#5a5f62",
        "surface-container-highest": "#e0e3e5",
        tertiary: "#924700",
        background: "#f7f9fb",
        outline: "#727785",
        "on-error": "#ffffff",
        "secondary-container": "#dce0e4",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        "primary-container": "#2170e4",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "outline-variant": "#c2c6d6",
        "on-primary-fixed-variant": "#004395",
        primary: "#0058be",
        "on-primary-fixed": "#001a42",
        "surface-container-low": "#f2f4f6",
        "on-surface": "#191c1e",
        "primary-fixed": "#d8e2ff",
        surface: "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#dfe3e7",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#311400",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#723600",
        "surface-tint": "#005ac2",
        "on-secondary-fixed-variant": "#43474b",
        "on-surface-variant": "#424754",
        "primary-fixed-dim": "#adc6ff",
        "secondary-fixed-dim": "#c3c7cb",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "8px",
        gutter: "24px",
        md: "16px",
        xl: "32px",
        "container-max": "1200px",
        lg: "24px",
        xs: "4px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        h1: ["Inter"],
        "label-md": ["Inter"],
        h2: ["Inter"],
        "body-lg": ["Inter"],
        h3: ["Inter"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        h1: [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        h2: [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        h3: ["18px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
